name: Composer

on:
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.4", "8.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate composer.json
        run: composer validate --strict
      - name: Install dependencies
        run: composer update --ansi --no-interaction

